apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: gvw0mdhhm1frln3hft9q/gitops-fc
  newTag: 117798cfb48c75bed4fa52232362348518e9c4b8
