name: CD GitOps

on:
  push:
    branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build and push image to Docker Hub
              uses: docker/build-push-action@v1.1.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: ${{ secrets.DOCKER_USERNAME }}/gitops-fc
                  tags: ${{ github.sha }}, latest